project:
  type: website

website:
  title: "Nyjil blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nyjil-john
        
output-dir: docs

format:
  html:
    theme:
      - cosmo
      
    css: styles.css
    toc: true

editor: visual

